version: '3'

services:

  mysql:
    image: mysql:5.7
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:  ${MYSQL_DATABASE}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD:  ${MYSQL_PASSWORD}
    restart: always

  wordpress:
    image: wordpress:latest
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAM}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - nginx:/etc/nginx/conf.d
      - ${WORDPRESS_VOLUME}:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress
  
  adminer:
    depends_on:
      - mysql
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    
  mailhog: 
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025
    restart: always
