version: '3.3'

services:
  mysql:
    restart: on-failure:5
    image: mysql:5.7
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
      TZ: ${TIMEZONE}
  wordpress:
    restart: on-failure:5
    depends_on:
      - mysql
    image: local-wordpress-xdebug
    container_name: local-wordpress-xdebug
    build:
      context: .
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
    volumes:
      - ${WORDPRESS_VOLUME}:/var/www/html
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: ${WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASS}
      WORDPRESS_DB_NAME: ${DATABASE}
      WP_DEBUG: ${WP_DEBUG}
      TZ: ${TIMEZONE}
       nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${NGINX_CONF_DIR:-./nginx}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
      - ${SSL_CERTS_DIR:-./certs}:/etc/letsencrypt
      - ${SSL_CERTS_DATA_DIR:-./certs-data}:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always
    
  adminer:
    restart: on-failure:5
    depends_on:
      - mysql
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
  mailhog:
    restart: on-failure:5
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_WEB_PORT}:8025
